name: 做饭记
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "17.0"
  generateEmptyDirectories: true

targets:
  做饭记:
    type: application
    platform: iOS
    sources:
      - path: 做饭记
        excludes:
          - "**/*.plist"
    info:
      path: 做饭记/Info.plist
      properties:
        CFBundleDisplayName: "What's Cooking"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSCameraUsageDescription: "需要访问相机来拍摄菜品照片"
        NSPhotoLibraryUsageDescription: "需要访问相册来选择菜品照片"
        UIUserInterfaceStyle: Light
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.example.zuofanji"
        DEVELOPMENT_TEAM: "3488U99HV8"
        CODE_SIGN_STYLE: "Automatic"
        TARGETED_DEVICE_FAMILY: "1"
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_EMIT_LOC_STRINGS: "YES"
